# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Building app for tests"
  lane :build do
    gym(scheme: "Kolokol", configuration: "Release", export_method: "development", output_directory: "./build")
  end

  desc "Testing app"
  lane :test do
    scan(scheme: "Kolokol", clean: true, parallel_testing: false)
  end
end
